Iter5
VladKvetkin/shortener pull request #5
Opened 2023-06-05 18:55 UTC by VladKvetkin

2023-06-06 22:03 UTC, valentinsoe requested changes
Спасибо, что сделал задание вовремя(и даже быстрее чем вовремя). Отлично, что соблюдаешь соглашения Go в контексте code style.
Решение с рандомом для сокращения на самом деле не самое удачное. Рекомендую самостоятельо подумать о том, к каким проблемам оно может приводить(одну я указал).

Некоторые мои комментарии не критичны, их можно оспаривать.
Но некоторые вещи(например хендлеры в пакете router) точно нужно исправить.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +	address, ok := os.LookupEnv("SERVER_ADDRESS")
Можно несколько сократить логику и сократить количество проверок, если читать конфигурацию в порядке возрастания приоритета:
Шаг 1: Ставим значения по умолчанию
Шаг 2: Читаем флаги(потенциально затираем значения по умолчанию)
Шаг 3: Читаем переменные окружения(потенциально затираем значения по умолчанию)

В таком случае не придется проверять, задано уже значение или нет на каждом этапе.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +	Host                string
У нас два раздельных поля - host и port.
Хотя фактически получаем мы их как единое целое, и даже создавая сервер их склеиваем обратно.
Зачем нам это разделение?

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +	ErrorInvalidURLAddress = errors.New("need valid address for short URL in a form scheme://host:port/")
Решение вынести ошибки с длинным текстом ошибок - хорошее.
Но почему-то вторая ошибка написана прямо в коде, хотя обе упоминаются в коде 1 раз.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +	if ok {
Также многие в таких случаях предпочитают короткую запись, вида
`if address, ok := os.LiookupEnv("SERVER_ADDRESS"); ok {`
Ее плюс не только в краткости, но и в данном случае мы сокращаем скоуп доступности переменной address.

Это можно не исправлять, это вкусовщина.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +func (c *Config) setBaseShortURL(baseShortURL string) error {
У данной функции расходятся название и функционал. Она не только устанавливает значение, но предварительно его валидирует. А еще это функция setter для публичного поля.
На мой взгляд лучше выставлять значение напрямую, а в конце чтения всей конфигурации, уже запускать валидацию(всей конфигурации)

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/config/config.go
> +	port, err = strconv.Atoi(splitAddress[1])
Тут тоже небольшое занудство добавлю. С одной стороны мы завалидировали, что порт конвертится к целому числу.
С другой мы все равно упадем при попытке создания сервера во множестве случаев, например port == -1 или port == 70000.
А также если в host будет написано что-то не то.и

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/router/router.go
> +func NewRouter(storage storage.Repositories, config config.Config) *Router {
Это единственная функция, которую я бы ожидал увидеть в роутере. Его отвественность - знать какой маршрут отправить в какой обработчик.
Код обработчиков лучше держать отдельно, и именно в него передавать storage и config. Потому что для управления маршрутами они на самом деле не нужны.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/shortener/shortener.go
> +		shortURL[i] = alphabet[rand.Intn(len(alphabet))]
Рекомендую подумать - какие проблемы будут в реальном мире от использования подобного алгоритма сокращения ссылки.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/router/router.go
> +	shortURL := r.storage.ReadByURL(string(body))
Лучше один раз сконвертировать body к строке. А не делать это трижды.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/router/router.go
> +	shortURL := r.storage.ReadByURL(string(body))
Также где возможно, лучше отказаться от проверок на default value. Лучше пользоваться возвратом двух значений - value и ok(как признак успеха) или value и err

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/router/router.go
> +	baseShortURLAddress := strings.TrimRight(r.config.BaseShortURLAddress, "/")
Это можно сделать один раз, когда мы сохраняем значение в конфиг.
Также при этом "муторный код" с проверками и "нормализацией" входящих данных будет в одном месте.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/storage/storage.go
> +type Storage struct {
В рамках данного инкремента не принципиально.
Но хотелось бы хранилище иметь в виде интерфейса, чтобы сразу зафиксировать сигнатуры методов, и когда начнем переходить на БД не менять сигнатуры.
Например во всех методах понадобится error на выходе, когда перейдем на любое "внешнее" хранилище. Ведь оно всегда может оказаться недоступным.

2023-06-06 22:03 UTC, valentinsoe commented on internal/app/storage/storage.go
> +	for key, value := range s.storage {
Вот тут явно проявляется негативный момент в алгоритме сокращения ссылки.
Мы хотим проверять, не сокращали ли еще такую ссылку. И для этого нам приходится проходить map не только по ключу(в функции выше), но и по значению.
При значительном количестве ссылок эта функция будет работать медленно.

Если даже оставлять такой подход, то возникает вопрос. Каких операций будет больше, сокращения ссылок или переходов по сокращенным?
И в зависимости от этого, что должно быть ключом, а что значением в map?

2023-06-08 19:07 UTC, valentinsoe requested changes
Супер! Остались прямо мелкие шероховатости и мои занудства про имена переменных/типов. 
Правильные имена сущностей одна из фундаментальных проблем программирования:)

Я закрыл вопросы с первого ревью, которые стали неактуальны. Но оставил парочку которые остались актуальными(про сам способ сокращения ссылок).
Они не влияют на прием PR, но я бы хотел про них подискутировать, если у тебя есть на это время.

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/config/config.go
> +	flag.Func("a", "HTTP server address", func(address string) error {
Можно еще немного это сократить, используя просто flag.String() передав в него значение по умолчанию, которое сейчас написано в конфиге.
Будет чуть проще и привычнее читать. Потому что если не видеть предыдущую итерацию данного PR, у меня бы возник вопрос - а зачем так сложно флаги объявлять?

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/handler/handler.go
> +	shortURL := chi.URLParam(req, "id")
Это можно не исправлять, просто позанудствую немного.
Мне не нравится имя переменной:)
В ней же не лежит URL, а идентификатор, по которому мы найдем полный URL.
Вот если бы мы хранили в map в качестве ключа не только id, а целиком сокращенный URL(чего делать на мой взгляд не надо), то тогда бы имя подходило.

И дальше это не самое удачное(на мой взгляд) имя переносится в имя функции.

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/shortener/shortener.go
> +	shortURLLenght := 8
Еще занудство: опечатка в слове Length:)

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/shortener/shortener.go
> +func CreateShortURL(randomNumber uint64) string {
А мы не можем тут получать randomNumber?
Ничего критичного в этом нет. Но таким образом все потребители нашей функции должны подключить пакет rand, вместо того, чтобы использовать его прямо тут.

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/storage/storage.go
> +type Repositories interface {
Тоже занудство про именование.
Интерфейс называется Repositories, что несколько размыто.
Есть не то, чтобы соглашение, но наверное хорошая практика называть интерфейс и структуру его реализующую следующим образом:
type InterfaceName interface {}
type ImplementationSpecificInterfaceName struct {}

Что в данном случае выглядело бы как
type Storage interface {}
type MemStorage struct {}

Что потом позволит добавить PostgresStorage, MongoStorage и прочие. И будет понятно что это реализации Storage, которые отличаются собственном тем, как производится хранение.

2023-06-08 19:07 UTC, valentinsoe commented on internal/app/shortener/shortener.go
> +		shortURL[i] = alphabet[rand.Intn(len(alphabet))]
Если есть время, мне бы хотелось все таки обсудить, какие еще способы генерации сокращенных ссылок ты видишь и какие у них плюсы и минусы.
Можно развести тред в пачке(идеальный вариант), можно ответить тут.
Задам наводящий вопрос:)
Можешь придумать способ, как сделать так, чтобы на одну и ту же ссылку алгоритм выдавал всегда один и тот же результат?
Какие это даст преимущества?

2023-06-09 12:30 UTC, VladKvetkin commented on internal/app/storage/storage.go
> +type Repositories interface {
Согласен, поправил.

2023-06-09 12:30 UTC, VladKvetkin commented on internal/app/shortener/shortener.go
> +func CreateShortURL(randomNumber uint64) string {
Поправил.

2023-06-09 12:30 UTC, VladKvetkin commented on internal/app/shortener/shortener.go
> +	shortURLLenght := 8
Поправил :)

2023-06-09 12:30 UTC, VladKvetkin commented on internal/app/handler/handler.go
> +	shortURL := chi.URLParam(req, "id")
Переделал имена методов и переменных с shortURL на id

2023-06-09 12:31 UTC, VladKvetkin commented on internal/app/config/config.go
> +	flag.Func("a", "HTTP server address", func(address string) error {
Сделал через flag.StringVar()

2023-06-09 12:31 UTC, VladKvetkin commented on internal/app/storage/storage.go
> +	for key, value := range s.storage {
Переходов по сокращенным будет больше. Я переделал хранение ключа и значения в мапе

2023-06-09 12:42 UTC, VladKvetkin commented
@valentinsoe 

По поводу алгоритма сокращения ссылок.

1. Я сделал простой алгоритм в самом начале в расчете, что мы его в будущем будем модернизировать, чтобы не бежать в перед паровоза, а сделать сначала простой, а далее улучшать. Этот алгоритм не безопасен, т.к. вероятность коллизий (повторяемость идентификатора для разных URL) крайне высока.

2. После 1-го PR погуглил алгоритмы сокращения ссылок, нашел алгоритм, суть которого представить число из десятичной системы счисления в 62 систему. Таким образом количество коллизий сводится к минимуму, т.к. вариантов идшников может быть 62 в 8 степени (8 - кол-во символов в сокращенной ссылке). Но все равно сохраняется ситуация, когда рандомное число может повториться для разных URL.

3. Отвечая на твой вопрос
> Можешь придумать способ, как сделать так, чтобы на одну и ту же ссылку алгоритм выдавал всегда один и тот же результат?

Да, можно использовать алгоритмы хеширования (sha256, md5, bcrypt), который для одного и того же URL всегда дадут один и тот же хеш. И уже от хеша брать его первые/последние 8 символов для короткой ссылки. Преимущества - нет рандома и соответственно ситуации, когда генерируется одно и то же число. Но я глубоко не знаю, как работают алгоритмы хеширования и какие у них коллизии могут возникнуть.

И еще в тесте у меня появился баг, но я его исправил. Можешь подсказать, почему так произошло ?
Проверка с багом: https://github.com/VladKvetkin/shortener/actions/runs/5221621320/jobs/9426458044?pr=5 (Тест Code Increment#2) **internal/app/handler/handler_test.go:81:16: internal compiler error: order.stmt CALLMETH**
Исправил баг в текущем коммите.

2023-06-09 15:14 UTC, valentinsoe commented
Ответ про генерацию ссылок - спасибо, принято. Колизии к сожалению возможны в любом случае.
Просто детерминированный алгоритм вычисления из исходной ссылки сокращенного ID позволяет быстрее проверять, есть ли у нас уже такая ссылка или нет.

Касательно ошибки компиляции тестов. Я честно скажу сам с таким не сталкивался. Гугл говорит о баге, который зарепортили, что проблема может случаться с замыканиями. Но у тебя не использовались замыкания.
Могу предположить что у компилятора поехала крыша немного когда у тебя в одном месте поле storage, пакет storage и переменная внутри анонимной функции тоже storage.

2023-06-09 15:18 UTC, valentinsoe approved these changes

2023-06-10 06:48 UTC, merged